In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import date

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
seattle = pd.read_csv('/content/drive/MyDrive/Data Science Final Project/SPD_Crime_Data__2008-Present_20260310.csv')

In [ ]:
seattle['Offense Date'] = pd.to_datetime(seattle['Offense Date'], format = '%Y %b %d %I:%M:%S %p').dt.date

In [ ]:
def sample_day(group):
  n = min(len(group), 1)
  return group.sample(n)

In [ ]:
seattle = df.groupby('Offense Date', group_keys=False).apply(sample_day)

In [ ]:
#add a column to sampled_df called City and every value is Seattle
seattle['City'] = 'Seattle'

In [ ]:
seattle_df = seattle[['Offense Date', 'City', 'NIBRS Offense Code Description']]

In [ ]:
chicago = pd.read_csv('/content/drive/MyDrive/Data Science Final Project/Crimes_-_2001_to_Present_20260310.csv')

In [ ]:
chicago['Date'] = pd.to_datetime(chicago['Date'], format = '%m/%d/%Y %I:%M:%S %p').dt.date

In [ ]:
#chicago = chicago.groupby('Date', group_keys=False).apply(sample_day)

In [ ]:
chicago['City'] = 'Chicago'

In [ ]:
la1 = pd.read_csv('/content/drive/MyDrive/Data Science Final Project/Arrest_Data_from_2010_to_2019_20260310.csv')

In [ ]:
chicago.head()

,ID,Case Number,Date,Block,Primary Type,Description,Location Description,Arrest,Domestic,Beat,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Latitude,Longitude,Location,City
0,13707849,JJ100011,2024-12-31,018XX W MAYPOLE AVE,CRIMINAL DAMAGE,TO PROPERTY,APARTMENT,False,False,1223,...,27.0,28.0,14,1164081.0,1901067.0,2024,41.884152,-87.672933,"(41.884152322, -87.672932576)",Chicago
1,13707986,JJ100019,2024-12-31,117XX S STATE ST,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,False,True,532,...,9.0,53.0,08B,1178352.0,1827293.0,2024,41.681396,-87.622767,"(41.68139574, -87.622767037)",Chicago
2,13707847,JJ100007,2024-12-31,029XX W CHICAGO AVE,CRIMINAL DAMAGE,TO CITY OF CHICAGO PROPERTY,CTA BUS,False,False,1211,...,36.0,24.0,14,1156857.0,1905197.0,2024,41.895635,-87.699348,"(41.895634912, -87.699347915)",Chicago
3,13707836,JJ100034,2024-12-31,0000X S OAKLEY BLVD,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,False,1223,...,27.0,28.0,07,1161090.0,1899804.0,2024,41.880749,-87.683951,"(41.880749175, -87.683950956)",Chicago
4,13709517,JJ101458,2024-12-31,047XX W HARRISON ST,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,False,1131,...,24.0,25.0,14,1144914.0,1896933.0,2024,41.873191,-87.743421,"(41.873191313, -87.743420863)",Chicago

In [ ]:
chicago_df = chicago[['Date', 'City', 'Primary Type']]

In [ ]:
la1['Arrest Date'] = pd.to_datetime(la1['Arrest Date'], format = '%m/%d/%Y').dt.date

In [ ]:
#la1 = la1.groupby('Arrest Date', group_keys=False).apply(sample_day)

In [ ]:
la1['City'] = 'Los Angeles'

In [ ]:
la1.head()

,Report ID,Report Type,Arrest Date,Time,Area ID,Area Name,Reporting District,Age,Sex Code,Descent Code,...,Address,Cross Street,LAT,LON,Location,Booking Date,Booking Time,Booking Location,Booking Location Code,City
0,180104095,RFC,2018-01-01,1530.0,1,Central,166,62,M,W,...,6TH,WALL ST,34.0435,-118.2471,POINT (-118.2471 34.0435),NaN,NaN,NaN,NaN,Los Angeles
1,180104096,RFC,2018-01-01,805.0,1,Central,158,32,F,O,...,7TH,KOHLER ST,34.0372,-118.2418,POINT (-118.2418 34.0372),NaN,NaN,NaN,NaN,Los Angeles
2,180104876,RFC,2018-01-01,1030.0,1,Central,158,48,M,B,...,7TH ST,GLADYS,34.0387,-118.2439,POINT (-118.2439 34.0387),NaN,NaN,NaN,NaN,Los Angeles
3,180604043,RFC,2018-01-01,1919.0,6,Hollywood,657,18,M,H,...,SIERRA VISTA,WESTERN AV,34.0896,-118.3092,POINT (-118.3092 34.0896),NaN,NaN,NaN,NaN,Los Angeles
4,180604231,RFC,2018-01-01,50.0,6,Hollywood,637,29,M,B,...,1700 VINE ST,NaN,34.1016,-118.3267,POINT (-118.3267 34.1016),NaN,NaN,NaN,NaN,Los Angeles

In [ ]:
la1_df = la1[['Arrest Date', 'City', 'Charge Group Description']]

In [ ]:
la2 = pd.read_csv('/content/drive/MyDrive/Data Science Final Project/Crime_Data_from_2020_to_2024.csv')

In [ ]:
la2['DATE OCC'] = pd.to_datetime(la2['DATE OCC'], format = '%m/%d/%Y %I:%M:%S %p').dt.date

In [ ]:
#la2 = la2.groupby('DATE OCC', group_keys=False).apply(sample_day)

In [ ]:
la2['City'] = 'Los Angeles'

In [ ]:
la2_df = la2[['DATE OCC', 'City', 'Crm Cd Desc']]

In [ ]:
ny = pd.read_csv('/content/drive/MyDrive/Data Science Final Project/NYPD_Arrests_Data_(Historic)_20260324.csv')

In [ ]:
ny['ARREST_DATE']= pd.to_datetime(ny['ARREST_DATE'], format = '%m/%d/%Y').dt.date

In [ ]:
#ny = ny.groupby('ARREST_DATE', group_keys=False).apply(sample_day)

In [ ]:
ny['City'] = 'New York'

In [ ]:
#make a new data frame with 'Arrest_Date', 'City', and 'PD_Desc'
ny_df = ny[['ARREST_DATE', 'City', 'PD_DESC']]

In [ ]:
seattle = seattle_df.rename(columns = {'Offense Date': 'Date', 'NIBRS Offense Code Description': 'Crime'})

In [ ]:
chicago = chicago_df.rename(columns = {'Primary Type': 'Crime'})

In [ ]:
#values in column crime
chicago['Crime'].unique()

array(['CRIMINAL DAMAGE', 'BATTERY', 'MOTOR VEHICLE THEFT',
       'OTHER OFFENSE', 'WEAPONS VIOLATION', 'ASSAULT', 'THEFT',
       'DECEPTIVE PRACTICE', 'CRIMINAL SEXUAL ASSAULT', 'ROBBERY',
       'CONCEALED CARRY LICENSE VIOLATION', 'BURGLARY', 'STALKING',
       'NARCOTICS', 'LIQUOR LAW VIOLATION', 'CRIMINAL TRESPASS',
       'OFFENSE INVOLVING CHILDREN', 'KIDNAPPING', 'HOMICIDE', 'ARSON',
       'SEX OFFENSE', 'INTERFERENCE WITH PUBLIC OFFICER',
       'PUBLIC PEACE VIOLATION', 'INTIMIDATION', 'GAMBLING',
       'PROSTITUTION', 'OBSCENITY', 'PUBLIC INDECENCY',
       'HUMAN TRAFFICKING', 'NON-CRIMINAL', 'OTHER NARCOTIC VIOLATION',
       'RITUALISM', 'CRIM SEXUAL ASSAULT'], dtype=object)

In [ ]:
la1 = la1_df.rename(columns = {'Charge Group Description': 'Crime', 'Arrest Date': 'Date'})

In [ ]:
la2 = la2_df.rename(columns = {'Crm Cd Desc': 'Crime', 'DATE OCC': 'Date'})

In [ ]:
la = pd.concat([la1, la2])

In [ ]:
ny = ny_df.rename(columns = {'ARREST_DATE': 'Date', 'PD_DESC': 'Crime'})

In [ ]:
sanfran = pd.read_csv("/content/drive/MyDrive/Data Science Final Project/Police_Department_Incident_Reports__2018_to_Present_20260413.csv")

In [ ]:
sanfran.head()

  Incident Date           Incident Subcategory
0    2024/08/13                          Other
1    2020/08/26          Larceny Theft - Other
2    2024/08/27          Larceny Theft - Other
3    2024/08/27  Larceny Theft - From Building
4    2024/09/08                   Intimidation

In [ ]:
sanfran['Incident Date']= pd.to_datetime(sanfran['Incident Date'], format = '%Y/%m/%d').dt.date

In [ ]:
sanfran = sanfran.rename(columns = {'Incident Date': 'Date', 'Incident Subcategory': 'Crime'})

In [ ]:
#sanfran = sanfran.groupby('Date', group_keys=False).apply(sample_day)

In [ ]:
sanfran['City'] = 'San Francisco'

In [ ]:
austin = pd.read_csv("/content/drive/MyDrive/Data Science Final Project/Crime_Reports_20260413.csv")

In [ ]:
austin.head()

          Highest Offense Description Occurred Date
0   AGGRAVATED ASSAULT-FAM/DATING VIO    01/01/2018
1         VIOL CITY ORDINANCE - OTHER    01/01/2018
2         AGG ASLT STRANGLE/SUFFOCATE    01/01/2018
3                         AGG ASSAULT    01/01/2018
4  ASSAULT WITH INJURY-FAM/DATING VIO    01/01/2018

In [ ]:
austin['Occurred Date']= pd.to_datetime(austin['Occurred Date'], format = '%m/%d/%Y').dt.date
austin = austin.rename(columns = {'Occurred Date': 'Date', 'Highest Offense Description': 'Crime'})
#austin = austin.groupby('Date', group_keys = False).apply(sample_day)
austin['City'] = 'Austin'

In [ ]:
detroit = pd.read_csv("/content/drive/MyDrive/Data Science Final Project/RMS_Crime_Incidents.csv")
detroit['incident_occurred_at']= pd.to_datetime(detroit['incident_occurred_at'], format = '%Y/%m/%d %H:%M:%S%z').dt.date
detroit = detroit.rename(columns = {'incident_occurred_at': 'Date', 'offense_description': 'Crime'})
#detroit = detroit.groupby('Date', group_keys = False).apply(sample_day)
detroit['City'] = 'Detroit'

In [ ]:
detroit = detroit[(detroit['Date'] >= date(2018, 1, 1)) &
                  (detroit['Date'] <= date(2024, 12, 31))]

In [ ]:
detroit.head()

                                  Crime        Date     City
0                   OBSTRUCTING JUSTICE  2018-01-11  Detroit
1   FAMILY - ABUSE / NEGLECT NONVIOLENT  2018-11-09  Detroit
7    ASSAULT AND BATTERY/SIMPLE ASSAULT  2018-04-23  Detroit
8         LARCENY - THEFT FROM BUILDING  2019-07-25  Detroit
10            LIQUOR VIOLATIONS - OTHER  2021-07-02  Detroit

In [ ]:
crime_df = pd.concat([seattle, chicago, la, ny, austin, sanfran, detroit])

In [ ]:
crime_df['Crime'].value_counts()

Crime
THEFT                                     431435
BATTERY                                   312718
CRIMINAL DAMAGE                           190381
ASSAULT 3                                 163634
MOTOR VEHICLE THEFT                       163037
                                           ...
CRIM NEG HOMICIDE/NON TRAFFIC                  1
POSSESSION OF A STOLEN VEHICLE                 1
ACCIDENTAL PROPERTY DAMAGE                     1
LOITERING 1ST DEGREE FOR DRUG PURPOSES         1
CHILD NEGLECT                                  1
Name: count, Length: 1282, dtype: int64

In [ ]:
!pip install thefuzz
from thefuzz import process

Collecting thefuzz
  Downloading thefuzz-0.22.1-py3-none-any.whl.metadata (3.9 kB)
Collecting rapidfuzz<4.0.0,>=3.0.0 (from thefuzz)
  Downloading rapidfuzz-3.14.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Downloading thefuzz-0.22.1-py3-none-any.whl (8.2 kB)
Downloading rapidfuzz-3.14.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 45.7 MB/s eta 0:00:00
Installing collected packages: rapidfuzz, thefuzz
Successfully installed rapidfuzz-3.14.5 thefuzz-0.22.1

In [ ]:
categories = ['Assault', 'Robbery', 'Homicide', 'Theft',
              'Burglary', 'Drug Offense', 'Sexual Assault', 'Vandalism', 'Trespassing', 'Battery']

In [ ]:
def match_crime(crime_type, threshold = 75):
  # Ensure crime_type is a string before processing
  crime_type_str = str(crime_type) if pd.notna(crime_type) else ''
  if not crime_type_str.strip(): # Handle empty or whitespace-only strings
      return 'Other'
  match, score = process.extractOne(crime_type_str, categories)
  return match if score >= threshold else 'Other'

crime_df['Crime Group'] = crime_df['Crime'].apply(match_crime)

WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']

In [ ]:
crime_df['Crime Group'].value_counts()

Crime Group
Other             3405422
Theft             1250022
Assault           1029515
Burglary           486539
Battery            319729
Robbery            220582
Vandalism          196684
Trespassing         95539
Drug Offense        76635
Sexual Assault       7568
Homicide             7524
Name: count, dtype: int64

In [ ]:
# Check what didn't match cleanly so you can handle edge cases
other_crimes = crime_df[crime_df['Crime Group'] == 'Other']['Crime'].value_counts()
print(other_crimes)

Crime
CRIMINAL DAMAGE                                                 190381
Larceny - From Vehicle                                          149650
DECEPTIVE PRACTICE                                              126749
LARCENY,PETIT FROM OPEN AREAS,                                  117570
VEHICLE - STOLEN                                                115184
                                                                 ...
HEROIN - POSSESS                                                     1
WEAPONS - CARRYING A CONCEALED WEAPON (CCW)                          1
FRAUD - NON SUFFICENT FUNDS CHECKS                                   1
LOST & FOUND PROPERTY                                                1
CHILD NEGLECT                                                        1
Name: count, Length: 1014, dtype: int64

In [ ]:
others = crime_df['Crime Group'] == 'Other'

In [ ]:
# Expand your categories with synonyms and alternate terms
expanded_categories = {
    'Theft'          : ['Theft', 'Larceny', 'Shoplifting', 'Stealing',
                        'Pickpocket', 'Pilfering', 'Stolen', 'Purse snatching', 'Vehicle, Stolen', 'Carjacking', 'Bunco'],
    'Assault'        : ['Assault', 'Battery', 'Intimidation',
                        'Threatening', 'Menacing', 'Harassment', 'Strangulation', 'Kidnapping', 'Coercion',
                        'Breath/Circ', 'AGG ASLT', 'Injury disabled individual'],
    'Drug Offense'   : ['Drug', 'Narcotics', 'Controlled Substance',
                        'Possession', 'Distribution', 'Cannabis', 'Marijuana', 'Meth'],
    'Fraud'          : ['Fraud', 'Forgery', 'Embezzlement', 'Deception',
                        'Identity Theft', 'Scam', 'Gambling', 'Credit Card', 'False Pretenses', 'Bad Checks', 'Money Laundering',
                        'Records Falsify', 'Counterfeiting', 'Peddling', 'Breach of Computer Security'],
    'Weapons'        : ['Weapons', 'Firearm', 'Gun', 'Armed', 'Carrying', 'Shots',
                        'Concealed Carry'],
    'Vandalism'      : ['Vandalism', 'Damage', 'Graffiti', 'Destruction', 'Arson', 'Criminal Mischief'],
    'Trespassing'    : ['Trespassing', 'Unlawful Entry', 'Breaking', 'Trespass'],
    'Public Order'   : ['Disorderly', 'Disturbing Peace', 'Public Intoxication',
                        'DUI', 'Loitering', 'Impersonation', 'Driving', 'Contempt',
                        'No Contact', 'Family Offenses', 'Terroristic Threat', 'Prowler', 'Public Peace',
                        'Riot', 'Bail Jumping', 'Resisting Arrest', 'Perjury', 'Conspiracy', 'Family Disturbance', 'Obstructing Justice',
                        'Suspicious Occ', 'DWI', 'DOC', 'DOC discharge gun'],
    'Misdemeanor'    : ['Misdemeanor', 'Liquor Law', 'Criminal Mis', 'Moving Traffic', 'Failure to Yield', 'Sale School Grounds', 'False Report'],
    'Sexual Misconduct' : ['Sexual Misconduct', 'Sex', 'Trafficking', 'Sex Offender', 'Pornography', 'Prostitution', 'Obscenity', 'Lewd', 'LETTERS, LEWD',
                           'CSC 1st Degree'],
    'Sexual Assault' : ['Rape', 'Sodomy', 'Exposure', 'Fondling', 'Oral Copulation', 'Forcible Touching'],
    'Other'          : ['Other', 'Recovered Vehicle', 'Lost Property', 'Miscellaneous Investigation',
                        'Warrant', 'Missing Adult'],
    'Animal Cruelty'  : ['Animal Cruelty', 'Animal'],
    'Child-Related Crimes' : ['Child', 'Endangerment', 'Crm Agnst Chld', 'Pre Delinquency', 'Online Solicitation of a Minor'],
    'Homicide' : ['Murder', 'Manslaughter'],
    'Terrorism' : ['Bomb Scare'],
    'Uncategorized' : ['Unclassified']

}

def second_fuzzy_pass(crime_label, threshold=70):
    # This function expects crime_label to be a native Python string due to the .astype(str) call below.
    # Defensive checks are still useful for clarity but less critical with prior type enforcement.
    crime_label_str = str(crime_label)
    if not crime_label_str.strip():
        return 'Other'

    best_score = 0
    best_category = 'Uncategorized'

    for category, synonyms in expanded_categories.items():
        match, score = process.extractOne(crime_label_str, synonyms)
        if score > best_score:
            best_score = score
            best_category = category

    return best_category if best_score >= threshold else 'Uncategorized'

# Ensure the 'Crime' column is of string type before applying fuzzy matching
# This is crucial to prevent TypeErrors from fuzzy matching library's C++ bindings
crime_df['Crime'] = crime_df['Crime'].astype(str)

# Apply ONLY to rows currently labeled Other
crime_df.loc[others, 'Crime Group'] = (
    crime_df.loc[others, 'Crime'].apply(second_fuzzy_pass)
)

Streaming output truncated to the last 5000 lines.
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-']

In [ ]:
crime_df.head()

In [ ]:
uncategorized = crime_df[crime_df['Crime Group'] == 'Uncategorized']['Crime'].value_counts()
print(uncategorized)

In [ ]:
#print all of uncategorized
print(crime_df[crime_df['Crime Group'] == 'Uncategorized']['Crime'].unique())

In [ ]:
crime_df['Crime Group'].value_counts()

In [ ]:
violence_weights = {
    'Homicide'             : 10,
    'Sexual Assault'       : 9,
    'Terrorism'            : 9,
    'Child-Related Crimes' : 8,
    'Robbery'              : 8,
    'Sexual Misconduct'    : 7,
    'Assault'              : 6,
    'Battery'              : 6,
    'Weapons'              : 5,
    'Burglary'             : 4,
    'Trespassing'          : 3,
    'Drug Offense'         : 2,
    'Vandalism'            : 2,
    'Fraud'                : 1,
    'Theft'                : 1,
    'Public Order'         : 2,
    'Animal Cruelty'       : 2,
    'Misdemeanor'          : 1,
    'Other'                : 0,
    'Uncategorized'        : 0
}

crime_df['Violence Rating'] = crime_df['Crime Group'].map(violence_weights)

In [ ]:
crime_df

In [ ]:
#create a new year column
crime_df['Year'] = pd.DatetimeIndex(crime_df['Date']).year

In [ ]:
crime_df

In [ ]:
#save as csv
crime_df.to_csv('crime_df.csv', index=False)